name: funkodreamstore_prototype
description: прототипчек
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.12.0
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  flutter_svg: ^2.0.7
  url_launcher: ^6.1.10
  image_picker: ^0.8.7+5
  image: ^4.1.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/cart.png
    - assets/images/
    - assets/images/main/
    - assets/images/nft/
    - assets/images/order/
    - assets/images/faq/
    - assets/images/check-list/
    - assets/images/about-us/

  fonts:
    - family: ProximaNova
      fonts:
        - asset: assets/fonts/ProximaNova-Regular.ttf
        - asset: assets/fonts/ProximaNova-Bold.otf
          weight: 700